

name: record github actions in this repo test

# Controls when the action will run.   

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-latest
    name: example
    steps:
      - uses: KittyJose/Insights@master          
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          super_secret: ${{ secrets.SuperSecret }}  
        with:
          json: ${{ toJSON(github) }}
          key: ${{ secrets.SuperSecret }}   
          database: "https://hub.terminusdb.com/db/admin/hub-actions"     


      
 



