

name: record github actions in this repo test

# Controls when the action will run.   

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: KittyJose/Insights@v1.0

    



 


      
 



