

name: record github actions in this repo test

# Controls when the action will run.   

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: KittyJose/Insights@v1
    - run: |
          npm install
          npm run build                 
    - name: Run the public action
      uses: ./
      with:
          json: ${{ toJSON(github) }}
          key: ${{ secrets.SuperSecret }}   
          database: "https://hub.terminusdb.com/db/admin/hub-actions" 
    - run: npm install
    - run: node index.js
    

 


      
 



