

name: record github actions in this repo 

# Controls when the action will run.   

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copying repo to GITHUB Work space
        uses: actions/checkout@v2
        with:
          repository: KittyJose/Insights
          ref: 'master'              
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install      
      - name: Get Inputs 
        env:
          JSON: ${{ toJSON(github) }}
          KEY: ${{ secrets.SuperSecret }}   
          DATABASE: "https://hub.terminusdb.com/db/admin/hub-actions"  
        run: |
          node index.js $JSON $KEY $DATABASE
 
     

   
