# This is a basic workflow to help you get started with Actions

name: post actions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  watch:
    types: [started, push]

jobs:
  create_star:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue using REST API
      run: |
        curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:4567/
