

name: record github actions in this repo test

# Controls when the action will run.   

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: KittyJose/Insights
        ref: 'master'  
        json: ${{ toJSON(github) }}
        key: ${{ secrets.SuperSecret }}   
        database: "https://hub.terminusdb.com/db/admin/hub-actions" 
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: node index.js

    



 


      
 



