# This is a basic workflow to help you get started with Actions

name: post actions

# Controls when the action will run. 
on:
  - push

jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue using REST API
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: | 
        curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST https://6b1b42be7dea.ngrok.io/payload

     
