

name: post actions

# Controls when the action will run.   

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: windows-latest
    name: example
    steps:
      - uses: KittyJose/Insights@master     
      - uses: actions/setup-node@v1
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          super_secret: ${{ secrets.SuperSecret }}  
        with:
          json: $GITHUB_CONTEXT
          key: ${{ secrets.SuperSecret }}   
          database: "https://hub.terminusdb.com/db/admin/hub-actions"     
          node-version: '12.x' 
      - run: npm install  
      - run: node index.js

      
 



