

name: post actions

# Controls when the action will run. 

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  one:
    runs-on: ubuntu-latest    
    steps:
      - name: set up envs and context
      - uses: KittyJose/Insights@master
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          super_secret: ${{ secrets.SuperSecret }}  
      - with:               
          json: $GITHUB_CONTEXT
          key: ${{ secrets.SuperSecret }}      
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: print first job output
      - with:
          node-version: '12.x'
      - run: npm install


         





