# This is a basic workflow to help you get started with Actions

name: post actions

# Controls when the action will run. 
on:
  - push

jobs:
  create_star:
    runs-on: ubuntu-latest
    steps:
    - name: Create issue using REST API
      run: |
        curl -d '{"key1":"value1", "key2":"value2"}' --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \ -X POST https://6b1b42be7dea.ngrok.io/
