

name: post actions

# Controls when the action will run.   sd

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  one:
    runs-on: ubuntu-latest    
    steps:
      - name: set up envs and context
        uses: KittyJose/Insights@master
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          super_secret: ${{ secrets.SuperSecret }}  
        with:               
          json: $GITHUB_CONTEXT
          key: ${{ secrets.SuperSecret }}   
          database: "https://hub.terminusdb.com/db/admin/hub-actions"
          node-version: '12.x'
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:     
      - name: print first job output      
        run: npm run start


         





