

name: record github actions in this repo test

# Controls when the action will run.   

on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: windows-latest
    steps:    
    - name: Install Dependencies
      run: npm install
    - name: using repo 
    - uses: KittyJose/Insights@v1


 


      
 



