

name: Record GitHub Actions 

# Script to record GitHub actions on a repo
on:
  push:
  pull_request:
  fork:
  issues:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      super_secret: ${{ secrets.SuperSecret }}  
      database: "https://hub.terminusdb.com/db/admin/hub-actions" 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: KittyJose/Insights
          ref: 'master'       
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install     
      - name: Install Client
        run: npm install --save @terminusdb/terminusdb-client           
      - name: Run Insights
        run: | 
           node index.js url:$database key:$super_secret json:"$GITHUB_CONTEXT" 
      
     
      
            
      
